<<<<<<< Updated upstream
=======
/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewCampaignRouteImport } from './routes/new-campaign'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign/index'
import { Route as CampaignSubmissionRouteImport } from './routes/campaign/submission'
import { Route as CampaignCreateRouteImport } from './routes/campaign/create'

const NewCampaignRoute = NewCampaignRouteImport.update({
  id: '/new-campaign',
  path: '/new-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/campaign/',
  path: '/campaign/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignSubmissionRoute = CampaignSubmissionRouteImport.update({
  id: '/campaign/submission',
  path: '/campaign/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCreateRoute = CampaignCreateRouteImport.update({
  id: '/campaign/create',
  path: '/campaign/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new-campaign': typeof NewCampaignRoute
  '/campaign/create': typeof CampaignCreateRoute
  '/campaign/submission': typeof CampaignSubmissionRoute
  '/campaign': typeof CampaignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new-campaign': typeof NewCampaignRoute
  '/campaign/create': typeof CampaignCreateRoute
  '/campaign/submission': typeof CampaignSubmissionRoute
  '/campaign': typeof CampaignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new-campaign': typeof NewCampaignRoute
  '/campaign/create': typeof CampaignCreateRoute
  '/campaign/submission': typeof CampaignSubmissionRoute
  '/campaign/': typeof CampaignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/new-campaign'
    | '/campaign/create'
    | '/campaign/submission'
    | '/campaign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/new-campaign'
    | '/campaign/create'
    | '/campaign/submission'
    | '/campaign'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new-campaign'
    | '/campaign/create'
    | '/campaign/submission'
    | '/campaign/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewCampaignRoute: typeof NewCampaignRoute
  CampaignCreateRoute: typeof CampaignCreateRoute
  CampaignSubmissionRoute: typeof CampaignSubmissionRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-campaign': {
      id: '/new-campaign'
      path: '/new-campaign'
      fullPath: '/new-campaign'
      preLoaderRoute: typeof NewCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/submission': {
      id: '/campaign/submission'
      path: '/campaign/submission'
      fullPath: '/campaign/submission'
      preLoaderRoute: typeof CampaignSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/create': {
      id: '/campaign/create'
      path: '/campaign/create'
      fullPath: '/campaign/create'
      preLoaderRoute: typeof CampaignCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewCampaignRoute: NewCampaignRoute,
  CampaignCreateRoute: CampaignCreateRoute,
  CampaignSubmissionRoute: CampaignSubmissionRoute,
  CampaignIndexRoute: CampaignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
>>>>>>> Stashed changes
